name: Scrape Latest Weather Data

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    # ADD THIS 2-LINE BLOCK TO GRANT PERMISSION
    permissions:
      contents: write
    # END OF NEW BLOCK

    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run scraper
        run: npm run scrape

      - name: Commit and push if data changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add public/data.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated data update"
            git push
          else
            echo "No changes to commit."
          fi